/** Complete local presentation catalog, validated by check-content-assets. */
export const courtroomVisuals = {
scenes: {"background/courtroom": "/content-packs/courtroom-demo/assets/courtroom.png", "background/witness-stand": "/content-packs/courtroom-demo/assets/witness-stand.png", "background/lobby": "/content-packs/courtroom-demo/assets/lobby.png"} as Record<string,string>,
sceneLabels: {"background/courtroom": "法庭", "background/witness-stand": "证人席", "background/lobby": "候审室"} as Record<string,string>,
stages: {"phoenix": {"background": "/content-packs/courtroom-demo/assets/defence.png", "foreground": "/content-packs/courtroom-demo/assets/defence-bench.png"}, "edgeworth": {"background": "/content-packs/courtroom-demo/assets/prosecution.png", "foreground": "/content-packs/courtroom-demo/assets/prosecution-bench.png"}, "judge": {"background": "/content-packs/courtroom-demo/assets/judgestand.png"}, "maya": {"background": "/content-packs/courtroom-demo/assets/witness-stand.png", "foreground": "/content-packs/courtroom-demo/assets/witness-bench.png"}, "witness": {"background": "/content-packs/courtroom-demo/assets/witness-stand.png", "foreground": "/content-packs/courtroom-demo/assets/witness-bench.png"}} as Record<string,{background:string;foreground?:string}>,
characters: {"phoenix": {"normal": "/content-packs/courtroom-demo/assets/phoenix-normal.png", "think": "/content-packs/courtroom-demo/assets/phoenix-think.png", "point": "/content-packs/courtroom-demo/assets/phoenix-point.png", "desk": "/content-packs/courtroom-demo/assets/phoenix-desk.png", "sweat": "/content-packs/courtroom-demo/assets/phoenix-sweat.png", "shocked": "/content-packs/courtroom-demo/assets/phoenix-shocked.png"}, "judge": {"normal": "/content-packs/courtroom-demo/assets/judge-normal.png", "stern": "/content-packs/courtroom-demo/assets/judge-stern.png", "surprised": "/content-packs/courtroom-demo/assets/judge-surprised.png", "confused": "/content-packs/courtroom-demo/assets/judge-confused.png"}, "edgeworth": {"normal": "/content-packs/courtroom-demo/assets/edgeworth-normal.gif", "bow": "/content-packs/courtroom-demo/assets/edgeworth-bow.gif", "point": "/content-packs/courtroom-demo/assets/edgeworth-point.gif", "smug": "/content-packs/courtroom-demo/assets/edgeworth-smug.gif", "surprised": "/content-packs/courtroom-demo/assets/edgeworth-surprised.gif", "damaged": "/content-packs/courtroom-demo/assets/edgeworth-damaged.gif"}, "maya": {"normal": "/content-packs/courtroom-demo/assets/maya-normal.gif", "cheer": "/content-packs/courtroom-demo/assets/maya-cheer.gif", "think": "/content-packs/courtroom-demo/assets/maya-think.gif", "surprised": "/content-packs/courtroom-demo/assets/maya-surprised.gif", "sad": "/content-packs/courtroom-demo/assets/maya-sad.gif"}, "witness": {"normal": "/content-packs/courtroom-demo/assets/witness-normal.gif", "nervous": "/content-packs/courtroom-demo/assets/witness-nervous.gif", "confident": "/content-packs/courtroom-demo/assets/witness-confident.gif", "shocked": "/content-packs/courtroom-demo/assets/witness-shocked.gif", "sweat": "/content-packs/courtroom-demo/assets/witness-sweat.gif"}} as Record<string,Record<string,string>>,
frames: {"/content-packs/courtroom-demo/assets/phoenix-desk.png": [256, 0, 256, 192], "/content-packs/courtroom-demo/assets/phoenix-shocked.png": [0, 384, 256, 192]} as Record<string,readonly [number,number,number,number]>,
colorKeySources: ["/content-packs/courtroom-demo/assets/defence-bench.png", "/content-packs/courtroom-demo/assets/prosecution-bench.png", "/content-packs/courtroom-demo/assets/witness-bench.png"] as string[]
};
